apiVersion: v1
kind: Pod
metadata:
  name: multi-pod
  namespace: namrata
  labels:
    app: multipod
spec:
   containers:
     - name: jupiter
       image: nginx
       env:
        - name: jupiter
          type: planet 
       ports:
        - containerPort: 80
     - name: europa
       image: busybox
       env:
        - name: europa
          type: moon 
       command: ["sleep", "4800"]
       ports:
        - containerPort: 80
