apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-webapp
  namespace: namrata
  labels:
    tier: frontend
    app: webapp
spec:
  replicas: 2
  selector:
     matchLabels:
       app: webapp
  template:
    metadata:
       labels:
          app: webapp
    spec:
      containers:
      - name: namrata-my-webapp
        image: nginx
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nams-frontend-service
  namespace: namrata
spec:
  type: NodePort
  selector:
    app: webapp
  ports:
  - name: nams-mywebapp
    protocol: TCP
    port: 80
    nodePort: 30083 
