apiVersion: v1
kind: PersistentVolume
metadata:
  name: custom-volume
  namespace: namrata
spec:
   accessModes:
     - ReadWriteMany
   capacity:
       storage: "50Mi"
   hostPath:
       path: /opt/data

