apiVersion: apps/v1
kind: Deployment
metadata:
  name: liveness-readiness-webapp
  namespace: namrata
  labels:
    name: liveness-readiness-webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: liveness-readiness-webapp
  template:
    metadata:
      labels:
        app: liveness-readiness-webapp
    spec:
        containers:
        - name: namrata-liveness-readiness
          image: nginx
          ports:
          - containerPort: 80
          livenessProbe:
               httpGet:
                 path: /api/healthy
                 port: 80
          readinessProbe:
               httpGet:
                 path: /api/ready
                 port: 80
               initialDelaySeconds: 10
               periodSeconds: 5
