apiVersion: apps/v1
kind: Deployment
metadata:
  name: namrata-deployment-clientserver
  namespace: namrata
  labels:
    app: nginx4
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx4
  template:
    metadata:
      labels:
        app: nginx4
    spec:
        containers:
        - name: namrata-clientserver
          image: nginx
          ports:
          - containerPort: 80
          resources:
            limits:
                cpu: "100m"
                memory: "100M"
            requests:
                cpu: "100m"
                memory: "100M"


