apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: namrata-hpa-clientserver
  namespace: namrata
spec:
  maxReplicas: 3
  minReplicas: 1 
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: namrata-deployment-clientserver
  targetCPUUtilizationPercentage: 30
