apiVersion: v1
kind: Service
metadata:
  name: namrata-nodeport-hr-web-app
  namespace: namrata
spec:
  type: NodePort
  selector:
    app: webapp
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30082
