apiVersion: v1
kind: Service
metadata:
  name: messaging-service
  namespace: namrata
  labels:
          tier: msg
spec:
  type: ClusterIP
  ports:
  - name: redis-apline
    protocol: TCP
    port: 6379
    targetPort: 6379

