apiVersion: v1
kind: Pod
metadata:
  name: nginx-resolver
  namespace: namrata
  labels:
    app: nginx2
spec:
   containers:
     - name: nams-nginx-resolver
       image: nginx
       ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-resolver-service
  namespace: namrata
spec:
  type: ClusterIP
  selector:
    app: nginx2
  ports:
  - name: nginx
    protocol: TCP
    port: 80
    targetPort: 80
